In [1]:
from google.colab import files
uploaded = files.upload()

Saving oews-2009-2025_original.csv to oews-2009-2025_original.csv

# Mapping the Barbering vs. Cosmetology Labor Landscape

In [4]:
import pandas as pd
import numpy as np

## Load the dataset

In [5]:
df = pd.read_csv("oews-2009-2025_original.csv")
df.head()

,Area Type,Area Name,Year,Quarter,Industry Name,Standard Occupational Classification,Occupational Title,Wage Type,Number of Employed,Mean Wage,10th Percentile Wage,25th Percentile Wage,50th Percentile (Median) Wage,75th Percentile Wage,90th Percentile Wage,Mean Relative Standard Error for Wage
0,Metropolitan Area,Anaheim-Santa Ana-Irvine MD,2009,1st Qtr,"Total, All Industries",0,"Total, All Occupations",Hourly wage,1525490.0,23.25,8.85,11.14,17.56,29.12,44.67,0.84
1,Metropolitan Area,Anaheim-Santa Ana-Irvine MD,2009,1st Qtr,"Total, All Industries",0,"Total, All Occupations",Annual wage or salary,1525490.0,48348.46,18403.65,23180.56,36541.93,60582.45,92903.56,0.84
2,Metropolitan Area,Anaheim-Santa Ana-Irvine MD,2009,1st Qtr,"Total, All Industries",110000,Management Occupations,Hourly wage,91260.0,56.62,24.04,34.48,50.61,72.58,0.00,0.80
3,Metropolitan Area,Anaheim-Santa Ana-Irvine MD,2009,1st Qtr,"Total, All Industries",110000,Management Occupations,Annual wage or salary,91260.0,117759.92,50006.38,71712.20,105266.68,150957.19,0.00,0.80
4,Metropolitan Area,Anaheim-Santa Ana-Irvine MD,2009,1st Qtr,"Total, All Industries",111011,Chief Executives,Hourly wage,3640.0,0.00,62.22,0.00,0.00,0.00,0.00,1.65

## Check the shape and columns

In [6]:
print(df.shape)
print(df.columns.tolist())

(547560, 16)
['Area Type', 'Area Name', 'Year', 'Quarter', 'Industry Name', 'Standard Occupational Classification', 'Occupational Title', 'Wage Type', 'Number of Employed', 'Mean Wage', '10th Percentile Wage', '25th Percentile Wage', '50th Percentile (Median) Wage', '75th Percentile Wage', '90th Percentile Wage', 'Mean Relative Standard Error for Wage']

## Clean the column names

In [7]:
df.columns = (
    df.columns
    .str.strip()
    .str.replace(r"\s+", " ", regex=True)
)

for col in df.columns:
    print(repr(col))

'Area Type'
'Area Name'
'Year'
'Quarter'
'Industry Name'
'Standard Occupational Classification'
'Occupational Title'
'Wage Type'
'Number of Employed'
'Mean Wage'
'10th Percentile Wage'
'25th Percentile Wage'
'50th Percentile (Median) Wage'
'75th Percentile Wage'
'90th Percentile Wage'
'Mean Relative Standard Error for Wage'

## Check whether the two required SOC codes exist

In this dataset, the occupation codes appear without hyphens:
- 395011 = Barbers
- 395012 = Hairdressers, Hairstylists, and Cosmetologists

In [8]:
target_codes = ["395011", "395012"]

filtered = df[df["Standard Occupational Classification"].astype(str).isin(target_codes)].copy()

print(filtered.shape)

filtered[[
    "Area Type",
    "Area Name",
    "Year",
    "Quarter",
    "Industry Name",
    "Standard Occupational Classification",
    "Occupational Title",
    "Number of Employed",
    "50th Percentile (Median) Wage"
]].head(20)

(1096, 16)

,Area Type,Area Name,Year,Quarter,Industry Name,Standard Occupational Classification,Occupational Title,Number of Employed,50th Percentile (Median) Wage
728,Metropolitan Area,Anaheim-Santa Ana-Irvine MD,2009,1st Qtr,"Total, All Industries",395012,"Hairdressers, Hairstylists, and Cosmetologists",2840.0,10.17
729,Metropolitan Area,Anaheim-Santa Ana-Irvine MD,2009,1st Qtr,"Total, All Industries",395012,"Hairdressers, Hairstylists, and Cosmetologists",2840.0,21149.17
1887,Metropolitan Area,Bakersfield MSA,2009,1st Qtr,"Total, All Industries",395012,"Hairdressers, Hairstylists, and Cosmetologists",0.0,9.76
1888,Metropolitan Area,Bakersfield MSA,2009,1st Qtr,"Total, All Industries",395012,"Hairdressers, Hairstylists, and Cosmetologists",0.0,20308.51
3151,California - Statewide,California,2009,1st Qtr,"Total, All Industries",395011,Barbers,620.0,11.53
3152,California - Statewide,California,2009,1st Qtr,"Total, All Industries",395011,Barbers,620.0,23981.31
3153,California - Statewide,California,2009,1st Qtr,"Total, All Industries",395012,"Hairdressers, Hairstylists, and Cosmetologists",23700.0,10.37
3154,California - Statewide,California,2009,1st Qtr,"Total, All Industries",395012,"Hairdressers, Hairstylists, and Cosmetologists",23700.0,21558.28
4304,Metropolitan Area,Chico MSA,2009,1st Qtr,"Total, All Industries",395012,"Hairdressers, Hairstylists, and Cosmetologists",100.0,9.65
4305,Metropolitan Area,Chico MSA,2009,1st Qtr,"Total, All Industries",395012,"Hairdressers, Hairstylists, and Cosmetologists",100.0,20072.84
5282,Metropolitan Area,El Centro MSA,2009,1st Qtr,"Total, All Industries",395012,"Hairdressers, Hairstylists, and Cosmetologists",50.0,10.33
5283,Metropolitan Area,El Centro MSA,2009,1st Qtr,"Total, All Industries",395012,"Hairdressers, Hairstylists, and Cosmetologists",50.0,21500.13
6100,Metropolitan Area,Fresno MSA,2009,1st Qtr,"Total, All Industries",395012,"Hairdressers, Hairstylists, and Cosmetologists",0.0,10.96
6101,Metropolitan Area,Fresno MSA,2009,1st Qtr,"Total, All Industries",395012,"Hairdressers, Hairstylists, and Cosmetologists",0.0,22799.89
6855,Metropolitan Area,Hanford-Corcoran MSA,2009,1st Qtr,"Total, All Industries",395012,"Hairdressers, Hairstylists, and Cosmetologists",60.0,9.34
6856,Metropolitan Area,Hanford-Corcoran MSA,2009,1st Qtr,"Total, All Industries",395012,"Hairdressers, Hairstylists, and Cosmetologists",60.0,19412.76
7842,Metropolitan Area,Los Angeles-Long Beach-Glendale Metro Div,2009,1st Qtr,"Total, All Industries",395011,Barbers,0.0,14.74
7843,Metropolitan Area,Los Angeles-Long Beach-Glendale Metro Div,2009,1st Qtr,"Total, All Industries",395011,Barbers,0.0,30672.93
7844,Metropolitan Area,Los Angeles-Long Beach-Glendale Metro Div,2009,1st Qtr,"Total, All Industries",395012,"Hairdressers, Hairstylists, and Cosmetologists",6310.0,10.02
7845,Metropolitan Area,Los Angeles-Long Beach-Glendale Metro Div,2009,1st Qtr,"Total, All Industries",395012,"Hairdressers, Hairstylists, and Cosmetologists",6310.0,20840.05

## Check the occupation counts

In [9]:
print(filtered["Occupational Title"].value_counts())

Occupational Title
Hairdressers, Hairstylists, and Cosmetologists    998
Barbers                                            98
Name: count, dtype: int64

## Check the available geography and time coverage

In [10]:
print("Unique areas:", filtered["Area Name"].nunique())
print("Years:", sorted(filtered["Year"].dropna().unique())[:10], "...", sorted(filtered["Year"].dropna().unique())[-10:])
print("Area types:", filtered["Area Type"].value_counts())

Unique areas: 49
Years: [np.int64(2009), np.int64(2010), np.int64(2011), np.int64(2012), np.int64(2013), np.int64(2014), np.int64(2015), np.int64(2016), np.int64(2017), np.int64(2018)] ... [np.int64(2016), np.int64(2017), np.int64(2018), np.int64(2019), np.int64(2020), np.int64(2021), np.int64(2022), np.int64(2023), np.int64(2024), np.int64(2025)]
Area types: Area Type
Metropolitan Area         952
OES Survey Region          76
California - Statewide     48
California-Statewide       20
Name: count, dtype: int64

# Step 2: Clean the OEWS dataset and create the focused subset

In this step, we keep the fields needed for the project, clean the numeric columns, and create a focused subset for the two required occupations.

## Keep only the columns needed for the project

In [11]:
columns_needed = [
    "Area Type",
    "Area Name",
    "Year",
    "Quarter",
    "Industry Name",
    "Standard Occupational Classification",
    "Occupational Title",
    "Number of Employed",
    "Mean Wage",
    "50th Percentile (Median) Wage"
]

oews = df[columns_needed].copy()
oews.head()

,Area Type,Area Name,Year,Quarter,Industry Name,Standard Occupational Classification,Occupational Title,Number of Employed,Mean Wage,50th Percentile (Median) Wage
0,Metropolitan Area,Anaheim-Santa Ana-Irvine MD,2009,1st Qtr,"Total, All Industries",0,"Total, All Occupations",1525490.0,23.25,17.56
1,Metropolitan Area,Anaheim-Santa Ana-Irvine MD,2009,1st Qtr,"Total, All Industries",0,"Total, All Occupations",1525490.0,48348.46,36541.93
2,Metropolitan Area,Anaheim-Santa Ana-Irvine MD,2009,1st Qtr,"Total, All Industries",110000,Management Occupations,91260.0,56.62,50.61
3,Metropolitan Area,Anaheim-Santa Ana-Irvine MD,2009,1st Qtr,"Total, All Industries",110000,Management Occupations,91260.0,117759.92,105266.68
4,Metropolitan Area,Anaheim-Santa Ana-Irvine MD,2009,1st Qtr,"Total, All Industries",111011,Chief Executives,3640.0,0.00,0.00

## Check missing values in the selected fields

In [12]:
print(oews.isnull().sum())

Area Type                                   0
Area Name                                   0
Year                                        0
Quarter                                     0
Industry Name                               0
Standard Occupational Classification        0
Occupational Title                         50
Number of Employed                      15676
Mean Wage                                9151
50th Percentile (Median) Wage           10931
dtype: int64

## Remove rows missing the core analysis fields

In [13]:
oews = oews.dropna(subset=[
    "Area Type",
    "Area Name",
    "Standard Occupational Classification",
    "Occupational Title",
    "Number of Employed",
    "50th Percentile (Median) Wage"
]).copy()

print(oews.shape)

(521777, 10)

## Convert employment and wage fields to numeric

In [14]:
numeric_cols = [
    "Number of Employed",
    "Mean Wage",
    "50th Percentile (Median) Wage"
]

for col in numeric_cols:
    oews[col] = pd.to_numeric(oews[col], errors="coerce")

print(oews[numeric_cols].dtypes)

Number of Employed               float64
Mean Wage                        float64
50th Percentile (Median) Wage    float64
dtype: object

## Remove rows that became invalid after numeric conversion

In [15]:
oews = oews.dropna(subset=["Number of Employed", "50th Percentile (Median) Wage"]).copy()
print(oews.shape)

(521777, 10)

## Create the focused subset for the two target occupations

In [16]:
target_codes = ["395011", "395012"]

focused = oews[oews["Standard Occupational Classification"].astype(str).isin(target_codes)].copy()
print(focused.shape)

focused[[
    "Area Type",
    "Area Name",
    "Year",
    "Quarter",
    "Industry Name",
    "Standard Occupational Classification",
    "Occupational Title",
    "Number of Employed",
    "50th Percentile (Median) Wage"
]].head(20)

(1016, 10)

,Area Type,Area Name,Year,Quarter,Industry Name,Standard Occupational Classification,Occupational Title,Number of Employed,50th Percentile (Median) Wage
728,Metropolitan Area,Anaheim-Santa Ana-Irvine MD,2009,1st Qtr,"Total, All Industries",395012,"Hairdressers, Hairstylists, and Cosmetologists",2840.0,10.17
729,Metropolitan Area,Anaheim-Santa Ana-Irvine MD,2009,1st Qtr,"Total, All Industries",395012,"Hairdressers, Hairstylists, and Cosmetologists",2840.0,21149.17
1887,Metropolitan Area,Bakersfield MSA,2009,1st Qtr,"Total, All Industries",395012,"Hairdressers, Hairstylists, and Cosmetologists",0.0,9.76
1888,Metropolitan Area,Bakersfield MSA,2009,1st Qtr,"Total, All Industries",395012,"Hairdressers, Hairstylists, and Cosmetologists",0.0,20308.51
3151,California - Statewide,California,2009,1st Qtr,"Total, All Industries",395011,Barbers,620.0,11.53
3152,California - Statewide,California,2009,1st Qtr,"Total, All Industries",395011,Barbers,620.0,23981.31
3153,California - Statewide,California,2009,1st Qtr,"Total, All Industries",395012,"Hairdressers, Hairstylists, and Cosmetologists",23700.0,10.37
3154,California - Statewide,California,2009,1st Qtr,"Total, All Industries",395012,"Hairdressers, Hairstylists, and Cosmetologists",23700.0,21558.28
4304,Metropolitan Area,Chico MSA,2009,1st Qtr,"Total, All Industries",395012,"Hairdressers, Hairstylists, and Cosmetologists",100.0,9.65
4305,Metropolitan Area,Chico MSA,2009,1st Qtr,"Total, All Industries",395012,"Hairdressers, Hairstylists, and Cosmetologists",100.0,20072.84
5282,Metropolitan Area,El Centro MSA,2009,1st Qtr,"Total, All Industries",395012,"Hairdressers, Hairstylists, and Cosmetologists",50.0,10.33
5283,Metropolitan Area,El Centro MSA,2009,1st Qtr,"Total, All Industries",395012,"Hairdressers, Hairstylists, and Cosmetologists",50.0,21500.13
6100,Metropolitan Area,Fresno MSA,2009,1st Qtr,"Total, All Industries",395012,"Hairdressers, Hairstylists, and Cosmetologists",0.0,10.96
6101,Metropolitan Area,Fresno MSA,2009,1st Qtr,"Total, All Industries",395012,"Hairdressers, Hairstylists, and Cosmetologists",0.0,22799.89
6855,Metropolitan Area,Hanford-Corcoran MSA,2009,1st Qtr,"Total, All Industries",395012,"Hairdressers, Hairstylists, and Cosmetologists",60.0,9.34
6856,Metropolitan Area,Hanford-Corcoran MSA,2009,1st Qtr,"Total, All Industries",395012,"Hairdressers, Hairstylists, and Cosmetologists",60.0,19412.76
7842,Metropolitan Area,Los Angeles-Long Beach-Glendale Metro Div,2009,1st Qtr,"Total, All Industries",395011,Barbers,0.0,14.74
7843,Metropolitan Area,Los Angeles-Long Beach-Glendale Metro Div,2009,1st Qtr,"Total, All Industries",395011,Barbers,0.0,30672.93
7844,Metropolitan Area,Los Angeles-Long Beach-Glendale Metro Div,2009,1st Qtr,"Total, All Industries",395012,"Hairdressers, Hairstylists, and Cosmetologists",6310.0,10.02
7845,Metropolitan Area,Los Angeles-Long Beach-Glendale Metro Div,2009,1st Qtr,"Total, All Industries",395012,"Hairdressers, Hairstylists, and Cosmetologists",6310.0,20840.05

## Create a short occupation group field

In [17]:
def map_occ_group(code):
    code = str(code)
    if code == "395011":
        return "Barbers"
    elif code == "395012":
        return "Cosmetologists"
    else:
        return "Other"

focused["Occupation_Group"] = focused["Standard Occupational Classification"].astype(str).apply(map_occ_group)

focused[[
    "Standard Occupational Classification",
    "Occupational Title",
    "Occupation_Group"
]].drop_duplicates()

,Standard Occupational Classification,Occupational Title,Occupation_Group
728,395012,"Hairdressers, Hairstylists, and Cosmetologists",Cosmetologists
3151,395011,Barbers,Barbers

## Preview the cleaned focused subset

In [18]:
print(focused.shape)
focused.head()

(1016, 11)

,Area Type,Area Name,Year,Quarter,Industry Name,Standard Occupational Classification,Occupational Title,Number of Employed,Mean Wage,50th Percentile (Median) Wage,Occupation_Group
728,Metropolitan Area,Anaheim-Santa Ana-Irvine MD,2009,1st Qtr,"Total, All Industries",395012,"Hairdressers, Hairstylists, and Cosmetologists",2840.0,11.19,10.17,Cosmetologists
729,Metropolitan Area,Anaheim-Santa Ana-Irvine MD,2009,1st Qtr,"Total, All Industries",395012,"Hairdressers, Hairstylists, and Cosmetologists",2840.0,23288.58,21149.17,Cosmetologists
1887,Metropolitan Area,Bakersfield MSA,2009,1st Qtr,"Total, All Industries",395012,"Hairdressers, Hairstylists, and Cosmetologists",0.0,11.22,9.76,Cosmetologists
1888,Metropolitan Area,Bakersfield MSA,2009,1st Qtr,"Total, All Industries",395012,"Hairdressers, Hairstylists, and Cosmetologists",0.0,23351.83,20308.51,Cosmetologists
3151,California - Statewide,California,2009,1st Qtr,"Total, All Industries",395011,Barbers,620.0,12.51,11.53,Barbers

## Check the counts by occupation and year

In [19]:
print(focused["Occupation_Group"].value_counts())
print(focused["Year"].value_counts().sort_index().tail(10))

Occupation_Group
Cosmetologists    942
Barbers            74
Name: count, dtype: int64
Year
2016    66
2017    72
2018    50
2019    48
2020    52
2021    44
2022    62
2023    58
2024    60
2025    60
Name: count, dtype: int64

# Step 3: Create Tableau-ready geographic and comparison fields

In this step, we create cleaner geography fields and a few helper fields that will make the Tableau dashboard easier to build.

## Create an area level field

This helps separate state-level rows from metropolitan-area rows.

In [20]:
def map_area_level(area_type):
    a = str(area_type).strip().lower()

    if "state" in a:
        return "State"
    elif "metro" in a or "metropolitan" in a:
        return "Metropolitan Area"
    else:
        return "Other"

focused["Area_Level"] = focused["Area Type"].apply(map_area_level)
focused[["Area Type", "Area_Level"]].drop_duplicates()

                     Area Type         Area_Level
728          Metropolitan Area  Metropolitan Area
3151    California - Statewide              State
12342        OES Survey Region              Other
272839    California-Statewide              State

## Create state and metro name helper fields

These make Tableau filters cleaner.

In [21]:
focused["State_Name"] = np.where(
    focused["Area_Level"] == "State",
    focused["Area Name"],
    np.nan
)

focused["Metro_Name"] = np.where(
    focused["Area_Level"] == "Metropolitan Area",
    focused["Area Name"],
    np.nan
)

focused[["Area Name", "Area_Level", "State_Name", "Metro_Name"]].head(15)

,Area Name,Area_Level,State_Name,Metro_Name
728,Anaheim-Santa Ana-Irvine MD,Metropolitan Area,NaN,Anaheim-Santa Ana-Irvine MD
729,Anaheim-Santa Ana-Irvine MD,Metropolitan Area,NaN,Anaheim-Santa Ana-Irvine MD
1887,Bakersfield MSA,Metropolitan Area,NaN,Bakersfield MSA
1888,Bakersfield MSA,Metropolitan Area,NaN,Bakersfield MSA
3151,California,State,California,NaN
3152,California,State,California,NaN
3153,California,State,California,NaN
3154,California,State,California,NaN
4304,Chico MSA,Metropolitan Area,NaN,Chico MSA
4305,Chico MSA,Metropolitan Area,NaN,Chico MSA
5282,El Centro MSA,Metropolitan Area,NaN,El Centro MSA
5283,El Centro MSA,Metropolitan Area,NaN,El Centro MSA
6100,Fresno MSA,Metropolitan Area,NaN,Fresno MSA
6101,Fresno MSA,Metropolitan Area,NaN,Fresno MSA
6855,Hanford-Corcoran MSA,Metropolitan Area,NaN,Hanford-Corcoran MSA


## Create a unified geography field

This provides one general name field for labels and tooltips.

In [22]:
focused["Geography_Name"] = focused["Area Name"]
focused[["Area Name", "Geography_Name"]].head()

                        Area Name               Geography_Name
728   Anaheim-Santa Ana-Irvine MD  Anaheim-Santa Ana-Irvine MD
729   Anaheim-Santa Ana-Irvine MD  Anaheim-Santa Ana-Irvine MD
1887              Bakersfield MSA              Bakersfield MSA
1888              Bakersfield MSA              Bakersfield MSA
3151                   California                   California

## Rename the core employment and wage fields for easier use in Tableau

In [23]:
focused = focused.rename(columns={
    "Number of Employed": "Employment",
    "50th Percentile (Median) Wage": "Median_Wage",
    "Mean Wage": "Mean_Wage",
    "Standard Occupational Classification": "SOC_Code"
})

focused.head()

,Area Type,Area Name,Year,Quarter,Industry Name,SOC_Code,Occupational Title,Employment,Mean_Wage,Median_Wage,Occupation_Group,Area_Level,State_Name,Metro_Name,Geography_Name
728,Metropolitan Area,Anaheim-Santa Ana-Irvine MD,2009,1st Qtr,"Total, All Industries",395012,"Hairdressers, Hairstylists, and Cosmetologists",2840.0,11.19,10.17,Cosmetologists,Metropolitan Area,NaN,Anaheim-Santa Ana-Irvine MD,Anaheim-Santa Ana-Irvine MD
729,Metropolitan Area,Anaheim-Santa Ana-Irvine MD,2009,1st Qtr,"Total, All Industries",395012,"Hairdressers, Hairstylists, and Cosmetologists",2840.0,23288.58,21149.17,Cosmetologists,Metropolitan Area,NaN,Anaheim-Santa Ana-Irvine MD,Anaheim-Santa Ana-Irvine MD
1887,Metropolitan Area,Bakersfield MSA,2009,1st Qtr,"Total, All Industries",395012,"Hairdressers, Hairstylists, and Cosmetologists",0.0,11.22,9.76,Cosmetologists,Metropolitan Area,NaN,Bakersfield MSA,Bakersfield MSA
1888,Metropolitan Area,Bakersfield MSA,2009,1st Qtr,"Total, All Industries",395012,"Hairdressers, Hairstylists, and Cosmetologists",0.0,23351.83,20308.51,Cosmetologists,Metropolitan Area,NaN,Bakersfield MSA,Bakersfield MSA
3151,California - Statewide,California,2009,1st Qtr,"Total, All Industries",395011,Barbers,620.0,12.51,11.53,Barbers,State,California,NaN,California

## Create a simple wage gap helper field

This can support quick comparisons between median and mean wage if needed.

In [24]:
focused["Wage_Gap"] = focused["Mean_Wage"] - focused["Median_Wage"]
focused[["Mean_Wage", "Median_Wage", "Wage_Gap"]].head()

      Mean_Wage  Median_Wage  Wage_Gap
728       11.19        10.17      1.02
729    23288.58     21149.17   2139.41
1887      11.22         9.76      1.46
1888   23351.83     20308.51   3043.32
3151      12.51        11.53      0.98

## Preview the Tableau-ready subset

In [25]:
print(focused.shape)
focused[[
    "Area Type",
    "Area_Level",
    "Area Name",
    "State_Name",
    "Metro_Name",
    "Year",
    "Quarter",
    "SOC_Code",
    "Occupation_Group",
    "Employment",
    "Median_Wage",
    "Mean_Wage"
]].head(20)

(1016, 16)

,Area Type,Area_Level,Area Name,State_Name,Metro_Name,Year,Quarter,SOC_Code,Occupation_Group,Employment,Median_Wage,Mean_Wage
728,Metropolitan Area,Metropolitan Area,Anaheim-Santa Ana-Irvine MD,NaN,Anaheim-Santa Ana-Irvine MD,2009,1st Qtr,395012,Cosmetologists,2840.0,10.17,11.19
729,Metropolitan Area,Metropolitan Area,Anaheim-Santa Ana-Irvine MD,NaN,Anaheim-Santa Ana-Irvine MD,2009,1st Qtr,395012,Cosmetologists,2840.0,21149.17,23288.58
1887,Metropolitan Area,Metropolitan Area,Bakersfield MSA,NaN,Bakersfield MSA,2009,1st Qtr,395012,Cosmetologists,0.0,9.76,11.22
1888,Metropolitan Area,Metropolitan Area,Bakersfield MSA,NaN,Bakersfield MSA,2009,1st Qtr,395012,Cosmetologists,0.0,20308.51,23351.83
3151,California - Statewide,State,California,California,NaN,2009,1st Qtr,395011,Barbers,620.0,11.53,12.51
3152,California - Statewide,State,California,California,NaN,2009,1st Qtr,395011,Barbers,620.0,23981.31,26018.69
3153,California - Statewide,State,California,California,NaN,2009,1st Qtr,395012,Cosmetologists,23700.0,10.37,12.22
3154,California - Statewide,State,California,California,NaN,2009,1st Qtr,395012,Cosmetologists,23700.0,21558.28,25432.06
4304,Metropolitan Area,Metropolitan Area,Chico MSA,NaN,Chico MSA,2009,1st Qtr,395012,Cosmetologists,100.0,9.65,10.25
4305,Metropolitan Area,Metropolitan Area,Chico MSA,NaN,Chico MSA,2009,1st Qtr,395012,Cosmetologists,100.0,20072.84,21329.75
5282,Metropolitan Area,Metropolitan Area,El Centro MSA,NaN,El Centro MSA,2009,1st Qtr,395012,Cosmetologists,50.0,10.33,10.39
5283,Metropolitan Area,Metropolitan Area,El Centro MSA,NaN,El Centro MSA,2009,1st Qtr,395012,Cosmetologists,50.0,21500.13,21604.19
6100,Metropolitan Area,Metropolitan Area,Fresno MSA,NaN,Fresno MSA,2009,1st Qtr,395012,Cosmetologists,0.0,10.96,14.18
6101,Metropolitan Area,Metropolitan Area,Fresno MSA,NaN,Fresno MSA,2009,1st Qtr,395012,Cosmetologists,0.0,22799.89,29487.44
6855,Metropolitan Area,Metropolitan Area,Hanford-Corcoran MSA,NaN,Hanford-Corcoran MSA,2009,1st Qtr,395012,Cosmetologists,60.0,9.34,10.31
6856,Metropolitan Area,Metropolitan Area,Hanford-Corcoran MSA,NaN,Hanford-Corcoran MSA,2009,1st Qtr,395012,Cosmetologists,60.0,19412.76,21463.40
7842,Metropolitan Area,Metropolitan Area,Los Angeles-Long Beach-Glendale Metro Div,NaN,Los Angeles-Long Beach-Glendale Metro Div,2009,1st Qtr,395011,Barbers,0.0,14.74,14.65
7843,Metropolitan Area,Metropolitan Area,Los Angeles-Long Beach-Glendale Metro Div,NaN,Los Angeles-Long Beach-Glendale Metro Div,2009,1st Qtr,395011,Barbers,0.0,30672.93,30471.95
7844,Metropolitan Area,Metropolitan Area,Los Angeles-Long Beach-Glendale Metro Div,NaN,Los Angeles-Long Beach-Glendale Metro Div,2009,1st Qtr,395012,Cosmetologists,6310.0,10.02,12.78
7845,Metropolitan Area,Metropolitan Area,Los Angeles-Long Beach-Glendale Metro Div,NaN,Los Angeles-Long Beach-Glendale Metro Div,2009,1st Qtr,395012,Cosmetologists,6310.0,20840.05,26590.01

In [28]:
focused["Area Name"].dropna().astype(str).drop_duplicates().tolist()[:50]

['Anaheim-Santa Ana-Irvine MD',
 'Bakersfield MSA',
 'California',
 'Chico MSA',
 'El Centro MSA',
 'Fresno MSA',
 'Hanford-Corcoran MSA',
 'Los Angeles-Long Beach-Glendale Metro Div',
 'Merced MSA',
 'Modesto MSA',
 'Napa MSA',
 'North Coast Region',
 'Oakland-Hayward-Berkeley Metro Div',
 'Oxnard-Thousand Oaks-Ventura MSA',
 'Redding MSA',
 'Riverside-San Bernardino-Ontario MSA',
 'Sacramento--Roseville--Arden-Arcade MSA',
 'Salinas MSA',
 'San Diego-Carlsbad MSA',
 'San Francisco-Redwood City-South San Francisco Metro Div',
 'San Jose-Sunnyvale-Santa Clara MSA',
 'San Luis Obispo-Paso Robles-Arroyo Grande MSA',
 'Santa Cruz-Watsonville MSA',
 'Santa Maria-Santa Barbara MSA',
 'Santa Rosa MSA',
 'Stockton-Lodi MSA',
 'Vallejo-Fairfield MSA',
 'Visalia-Porterville MSA',
 'Yuba City MSA',
 'Mother Lode Region',
 'North Valley Region',
 'Northern Mountains Region',
 'Chico',
 'Madera MSA',
 'San Rafael MD',
 'North Valley-Northern Mountains Region',
 'Los Angeles-Long Beach-Glendale MD',
 'Oakland-Hayward-Berkeley MD',
 'Sacramento-Roseville-Arden Arcade MSA',
 'San Francisco-Redwood City-South San Francisco MD',
 'Bakersfield-Delano MSA',
 'Sacramento-Roseville-Folsom MSA',
 'San Diego-Chula Vista-Carlsbad MSA',
 'San Luis Obispo-Paso Robles MSA',
 'Santa Rosa-Petaluma MSA',
 'Vallejo MSA',
 'Visalia MSA',
 'Oakland-Fremont-Berkeley MD',
 'San Francisco-San Mateo-Redwood City MD']

## Save the final Tableau-ready dataset

In [26]:
focused.to_csv("barber_cosmetology_oews_ready.csv", index=False)
print("Saved as barber_cosmetology_oews_ready.csv")

Saved as barber_cosmetology_oews_ready.csv

## Download the final dataset in Google Colab

In [27]:
from google.colab import files
files.download("barber_cosmetology_oews_ready.csv")