# Online Retail Dataset Cleaning for Cohort Analysis

This notebook cleans the online retail dataset so it can be used for customer cohort retention analysis in Tableau.

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving online_retail.csv to online_retail.csv

In [ ]:
import pandas as pd

## Load the dataset

In [ ]:
df = pd.read_csv("online_retail.csv", encoding="ISO-8859-1")
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [ ]:
print(df.shape)
print(df.columns.tolist())

(541909, 8)
['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate', 'UnitPrice', 'CustomerID', 'Country']

In [ ]:
columns_needed = [
    "InvoiceNo",
    "Description",
    "Quantity",
    "InvoiceDate",
    "UnitPrice",
    "CustomerID",
    "Country"
]

df = df[columns_needed].copy()
df.head()

,InvoiceNo,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [ ]:
df = df.dropna(subset=["CustomerID"]).copy()
print(df.shape)

(406829, 7)

In [ ]:
df["CustomerID"] = df["CustomerID"].astype(int)
df.head()

,InvoiceNo,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850,United Kingdom
1,536365,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850,United Kingdom
2,536365,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850,United Kingdom
3,536365,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850,United Kingdom
4,536365,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850,United Kingdom

In [ ]:
df["InvoiceDate"] = pd.to_datetime(df["InvoiceDate"])
df.dtypes

InvoiceNo              object
Description            object
Quantity                int64
InvoiceDate    datetime64[ns]
UnitPrice             float64
CustomerID              int64
Country                object
dtype: object

## Remove cancelled transactions

In this dataset, cancelled invoices usually begin with "C".
These are removed because they do not represent successful purchases.

In [ ]:
df = df[~df["InvoiceNo"].astype(str).str.startswith("C")].copy()
print(df.shape)

(397924, 7)

## Remove invalid quantity and price values

Only positive quantity and positive unit price values should be kept.

In [ ]:
df = df[(df["Quantity"] > 0) & (df["UnitPrice"] > 0)].copy()
print(df.shape)

(397884, 7)

## Create Total Amount

This is optional for the cohort dashboard, but useful for extra analysis.

In [ ]:
df["TotalAmount"] = df["Quantity"] * df["UnitPrice"]
df.head()

,InvoiceNo,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalAmount
0,536365,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850,United Kingdom,15.30
1,536365,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34
2,536365,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850,United Kingdom,22.00
3,536365,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34
4,536365,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34

## Check the cleaned dataset

In [ ]:
print(df.shape)
print(df["CustomerID"].nunique(), "unique customers")
print(df["InvoiceDate"].min(), "to", df["InvoiceDate"].max())

(397884, 8)
4338 unique customers
2010-12-01 08:26:00 to 2011-12-09 12:50:00

## Save the cleaned dataset

In [ ]:
df.to_csv("online_retail_cleaned.csv", index=False)
print("Saved as online_retail_cleaned.csv")

Saved as online_retail_cleaned.csv

## Download the cleaned dataset in Google Colab

In [ ]:
from google.colab import files
files.download("online_retail_cleaned.csv")