# YouTube Engagement Trends Dashboard for Vivid-Sync Media

This notebook prepares the YouTube trending videos dataset for Tableau analysis focused on engagement score, category comparison, and trend analysis.

In [1]:
import pandas as pd
import numpy as np

## Load the dataset

In [3]:
from google.colab import files
uploaded = files.upload()

Saving CAvideos.csv to CAvideos (1).csv

In [4]:
df = pd.read_csv("CAvideos.csv")
df.head()

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description
0,n1WpP7iowLc,17.14.11,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10,2017-11-10T17:00:03.000Z,"Eminem|""Walk""|""On""|""Water""|""Aftermath/Shady/In...",17158579,787425,43420,125882,https://i.ytimg.com/vi/n1WpP7iowLc/default.jpg,False,False,False,Eminem's new track Walk on Water ft. Beyoncé i...
1,0dBIkQ4Mz1M,17.14.11,PLUSH - Bad Unboxing Fan Mail,iDubbbzTV,23,2017-11-13T17:00:00.000Z,"plush|""bad unboxing""|""unboxing""|""fan mail""|""id...",1014651,127794,1688,13030,https://i.ytimg.com/vi/0dBIkQ4Mz1M/default.jpg,False,False,False,STill got a lot of packages. Probably will las...
2,5qpjK5DgCt4,17.14.11,"Racist Superman | Rudy Mancuso, King Bach & Le...",Rudy Mancuso,23,2017-11-12T19:05:24.000Z,"racist superman|""rudy""|""mancuso""|""king""|""bach""...",3191434,146035,5339,8181,https://i.ytimg.com/vi/5qpjK5DgCt4/default.jpg,False,False,False,WATCH MY PREVIOUS VIDEO ▶ \n\nSUBSCRIBE ► http...
3,d380meD0W0M,17.14.11,I Dare You: GOING BALD!?,nigahiga,24,2017-11-12T18:01:41.000Z,"ryan|""higa""|""higatv""|""nigahiga""|""i dare you""|""...",2095828,132239,1989,17518,https://i.ytimg.com/vi/d380meD0W0M/default.jpg,False,False,False,I know it's been a while since we did this sho...
4,2Vv-BfVoq4g,17.14.11,Ed Sheeran - Perfect (Official Music Video),Ed Sheeran,10,2017-11-09T11:04:14.000Z,"edsheeran|""ed sheeran""|""acoustic""|""live""|""cove...",33523622,1634130,21082,85067,https://i.ytimg.com/vi/2Vv-BfVoq4g/default.jpg,False,False,False,🎧: https://ad.gt/yt-perfect\n💰: https://atlant...

## Check the dataset shape and columns

In [5]:
print(df.shape)
print(df.columns.tolist())

(40881, 16)
['video_id', 'trending_date', 'title', 'channel_title', 'category_id', 'publish_time', 'tags', 'views', 'likes', 'dislikes', 'comment_count', 'thumbnail_link', 'comments_disabled', 'ratings_disabled', 'video_error_or_removed', 'description']

## Check missing values in the main fields

In [6]:
main_fields = [
    "trending_date",
    "title",
    "channel_title",
    "category_id",
    "publish_time",
    "views",
    "likes",
    "comment_count"
]

print(df[main_fields].isnull().sum())

trending_date    0
title            0
channel_title    0
category_id      0
publish_time     0
views            0
likes            0
comment_count    0
dtype: int64

## Preview the core analysis fields

In [7]:
df[[
    "trending_date",
    "title",
    "channel_title",
    "category_id",
    "views",
    "likes",
    "comment_count"
]].head(15)

,trending_date,title,channel_title,category_id,views,likes,comment_count
0,17.14.11,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10,17158579,787425,125882
1,17.14.11,PLUSH - Bad Unboxing Fan Mail,iDubbbzTV,23,1014651,127794,13030
2,17.14.11,"Racist Superman | Rudy Mancuso, King Bach & Le...",Rudy Mancuso,23,3191434,146035,8181
3,17.14.11,I Dare You: GOING BALD!?,nigahiga,24,2095828,132239,17518
4,17.14.11,Ed Sheeran - Perfect (Official Music Video),Ed Sheeran,10,33523622,1634130,85067
5,17.14.11,Jake Paul Says Alissa Violet CHEATED with LOGA...,DramaAlert,25,1309699,103755,12143
6,17.14.11,Vanoss Superhero School - New Students,VanossGaming,23,2987945,187464,26629
7,17.14.11,WE WANT TO TALK ABOUT OUR MARRIAGE,CaseyNeistat,22,748374,57534,15959
8,17.14.11,THE LOGANG MADE HISTORY. LOL. AGAIN.,Logan Paul Vlogs,24,4477587,292837,36391
9,17.14.11,Finally Sheldon is winning an argument about t...,Sheikh Musa,22,505161,4135,1484
10,17.14.11,21 Savage - Bank Account (Official Music Video),21 Savage,10,5068229,263596,28976
11,17.14.11,12 Weird Ways To Sneak Food Into Class / Back ...,Troom Troom,26,3153224,28451,3312
12,17.14.11,猎场 | Game Of Hunting 12【TV版】（胡歌、張嘉譯、祖峰等主演）,大劇獨播,1,158815,218,186
13,17.14.11,Daang ( Full Video ) | Mankirt Aulakh | Sukh S...,Speed Records,10,5718766,127477,8063
14,17.14.11,YOUTUBERS REACT TO TOP 10 TWITTER ACCOUNTS OF ...,FBE,24,960747,31810,5335

## Check basic numeric ranges

In [8]:
df[[
    "views",
    "likes",
    "comment_count"
]].describe()

              views         likes  comment_count
count  4.088100e+04  4.088100e+04   4.088100e+04
mean   1.147036e+06  3.958269e+04   5.042975e+03
std    3.390913e+06  1.326895e+05   2.157902e+04
min    7.330000e+02  0.000000e+00   0.000000e+00
25%    1.439020e+05  2.191000e+03   4.170000e+02
50%    3.712040e+05  8.780000e+03   1.301000e+03
75%    9.633020e+05  2.871700e+04   3.713000e+03
max    1.378431e+08  5.053338e+06   1.114800e+06

## Create a simple source region field

Since this file is the Canada trending file, we label the source region clearly.

In [9]:
df["Region"] = "Canada"
df[["title", "Region"]].head()

                                               title  Region
0         Eminem - Walk On Water (Audio) ft. Beyoncé  Canada
1                      PLUSH - Bad Unboxing Fan Mail  Canada
2  Racist Superman | Rudy Mancuso, King Bach & Le...  Canada
3                           I Dare You: GOING BALD!?  Canada
4        Ed Sheeran - Perfect (Official Music Video)  Canada

# Step 2: Clean the dataset and create Tableau-ready time fields

In this step, we clean the core YouTube fields, convert the date columns, ensure numeric columns are valid, and create helper fields for time-based Tableau analysis.

## Keep only the fields needed for the project

In [10]:
columns_needed = [
    "video_id",
    "trending_date",
    "title",
    "channel_title",
    "category_id",
    "publish_time",
    "views",
    "likes",
    "comment_count",
    "Region"
]

df = df[columns_needed].copy()
df.head()

,video_id,trending_date,title,channel_title,category_id,publish_time,views,likes,comment_count,Region
0,n1WpP7iowLc,17.14.11,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10,2017-11-10T17:00:03.000Z,17158579,787425,125882,Canada
1,0dBIkQ4Mz1M,17.14.11,PLUSH - Bad Unboxing Fan Mail,iDubbbzTV,23,2017-11-13T17:00:00.000Z,1014651,127794,13030,Canada
2,5qpjK5DgCt4,17.14.11,"Racist Superman | Rudy Mancuso, King Bach & Le...",Rudy Mancuso,23,2017-11-12T19:05:24.000Z,3191434,146035,8181,Canada
3,d380meD0W0M,17.14.11,I Dare You: GOING BALD!?,nigahiga,24,2017-11-12T18:01:41.000Z,2095828,132239,17518,Canada
4,2Vv-BfVoq4g,17.14.11,Ed Sheeran - Perfect (Official Music Video),Ed Sheeran,10,2017-11-09T11:04:14.000Z,33523622,1634130,85067,Canada

## Remove rows with missing values in the core fields

In [11]:
df = df.dropna(subset=[
    "trending_date",
    "title",
    "channel_title",
    "category_id",
    "publish_time",
    "views",
    "likes",
    "comment_count"
]).copy()

print(df.shape)

(40881, 10)

## Convert the numeric fields to numeric type

In [12]:
for col in ["views", "likes", "comment_count", "category_id"]:
    df[col] = pd.to_numeric(df[col], errors="coerce")

print(df[["views", "likes", "comment_count", "category_id"]].dtypes)

views            int64
likes            int64
comment_count    int64
category_id      int64
dtype: object

## Remove rows that became invalid after numeric conversion

In [13]:
df = df.dropna(subset=["views", "likes", "comment_count", "category_id"]).copy()
print(df.shape)

(40881, 10)

## Convert publish time to datetime

In [14]:
df["publish_time"] = pd.to_datetime(df["publish_time"], errors="coerce")
print(df["publish_time"].dtype)

datetime64[ns, UTC]

## Convert trending date to datetime

The trending_date field in this dataset uses a short year format like YY.DD.MM.

In [15]:
df["trending_date"] = pd.to_datetime(df["trending_date"], format="%y.%d.%m", errors="coerce")
print(df["trending_date"].dtype)

datetime64[ns]

## Remove rows with invalid converted dates

In [16]:
df = df.dropna(subset=["publish_time", "trending_date"]).copy()
print(df.shape)

(40881, 10)

## Create helper date fields for Tableau

In [17]:
df["Trending_Month"] = df["trending_date"].dt.to_period("M").astype(str)
df["Trending_Week"] = df["trending_date"].dt.to_period("W").astype(str)
df["Trending_Year"] = df["trending_date"].dt.year

df[["trending_date", "Trending_Month", "Trending_Week", "Trending_Year"]].head()

  trending_date Trending_Month          Trending_Week  Trending_Year
0    2017-11-14        2017-11  2017-11-13/2017-11-19           2017
1    2017-11-14        2017-11  2017-11-13/2017-11-19           2017
2    2017-11-14        2017-11  2017-11-13/2017-11-19           2017
3    2017-11-14        2017-11  2017-11-13/2017-11-19           2017
4    2017-11-14        2017-11  2017-11-13/2017-11-19           2017

## Preview the cleaned dataset

In [18]:
print(df.shape)
df.head()

(40881, 13)

,video_id,trending_date,title,channel_title,category_id,publish_time,views,likes,comment_count,Region,Trending_Month,Trending_Week,Trending_Year
0,n1WpP7iowLc,2017-11-14,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10,2017-11-10 17:00:03+00:00,17158579,787425,125882,Canada,2017-11,2017-11-13/2017-11-19,2017
1,0dBIkQ4Mz1M,2017-11-14,PLUSH - Bad Unboxing Fan Mail,iDubbbzTV,23,2017-11-13 17:00:00+00:00,1014651,127794,13030,Canada,2017-11,2017-11-13/2017-11-19,2017
2,5qpjK5DgCt4,2017-11-14,"Racist Superman | Rudy Mancuso, King Bach & Le...",Rudy Mancuso,23,2017-11-12 19:05:24+00:00,3191434,146035,8181,Canada,2017-11,2017-11-13/2017-11-19,2017
3,d380meD0W0M,2017-11-14,I Dare You: GOING BALD!?,nigahiga,24,2017-11-12 18:01:41+00:00,2095828,132239,17518,Canada,2017-11,2017-11-13/2017-11-19,2017
4,2Vv-BfVoq4g,2017-11-14,Ed Sheeran - Perfect (Official Music Video),Ed Sheeran,10,2017-11-09 11:04:14+00:00,33523622,1634130,85067,Canada,2017-11,2017-11-13/2017-11-19,2017

# Step 3: Create category labels and save the Tableau-ready dataset

In this step, we map the YouTube category IDs to readable category names, create a cleaner category field for Tableau, and save the final dataset.

## Map category IDs to readable YouTube category names

In [19]:
category_map = {
    1: "Film & Animation",
    2: "Autos & Vehicles",
    10: "Music",
    15: "Pets & Animals",
    17: "Sports",
    18: "Short Movies",
    19: "Travel & Events",
    20: "Gaming",
    21: "Videoblogging",
    22: "People & Blogs",
    23: "Comedy",
    24: "Entertainment",
    25: "News & Politics",
    26: "Howto & Style",
    27: "Education",
    28: "Science & Technology",
    29: "Nonprofits & Activism",
    30: "Movies",
    31: "Anime/Animation",
    32: "Action/Adventure",
    33: "Classics",
    34: "Comedy",
    35: "Documentary",
    36: "Drama",
    37: "Family",
    38: "Foreign",
    39: "Horror",
    40: "Sci-Fi/Fantasy",
    41: "Thriller",
    42: "Shorts",
    43: "Shows",
    44: "Trailers"
}

df["Category"] = df["category_id"].map(category_map).fillna("Other")
df[["category_id", "Category"]].drop_duplicates().sort_values("category_id").head(20)

       category_id               Category
12               1       Film & Animation
86               2       Autos & Vehicles
0               10                  Music
53              15         Pets & Animals
41              17                 Sports
66              19        Travel & Events
33              20                 Gaming
7               22         People & Blogs
1               23                 Comedy
3               24          Entertainment
5               25        News & Politics
11              26          Howto & Style
140             27              Education
20              28   Science & Technology
43              29  Nonprofits & Activism
37939           30                 Movies
264             43                  Shows

## Check category distribution

In [20]:
df["Category"].value_counts().head(20)

Category
Entertainment            13451
News & Politics           4159
People & Blogs            4105
Comedy                    3773
Music                     3731
Sports                    2787
Film & Animation          2060
Howto & Style             2007
Gaming                    1344
Science & Technology      1155
Education                  991
Travel & Events            392
Pets & Animals             369
Autos & Vehicles           353
Shows                      124
Nonprofits & Activism       74
Movies                       6
Name: count, dtype: int64

## Standardize text fields

In [21]:
for col in ["title", "channel_title", "Category", "Region"]:
    df[col] = df[col].astype(str).str.strip()

df.head()

,video_id,trending_date,title,channel_title,category_id,publish_time,views,likes,comment_count,Region,Trending_Month,Trending_Week,Trending_Year,Category
0,n1WpP7iowLc,2017-11-14,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10,2017-11-10 17:00:03+00:00,17158579,787425,125882,Canada,2017-11,2017-11-13/2017-11-19,2017,Music
1,0dBIkQ4Mz1M,2017-11-14,PLUSH - Bad Unboxing Fan Mail,iDubbbzTV,23,2017-11-13 17:00:00+00:00,1014651,127794,13030,Canada,2017-11,2017-11-13/2017-11-19,2017,Comedy
2,5qpjK5DgCt4,2017-11-14,"Racist Superman | Rudy Mancuso, King Bach & Le...",Rudy Mancuso,23,2017-11-12 19:05:24+00:00,3191434,146035,8181,Canada,2017-11,2017-11-13/2017-11-19,2017,Comedy
3,d380meD0W0M,2017-11-14,I Dare You: GOING BALD!?,nigahiga,24,2017-11-12 18:01:41+00:00,2095828,132239,17518,Canada,2017-11,2017-11-13/2017-11-19,2017,Entertainment
4,2Vv-BfVoq4g,2017-11-14,Ed Sheeran - Perfect (Official Music Video),Ed Sheeran,10,2017-11-09 11:04:14+00:00,33523622,1634130,85067,Canada,2017-11,2017-11-13/2017-11-19,2017,Music

## Optional: check for zero-view rows

This matters because the Engagement Score in Tableau must avoid division by zero.

In [22]:
print("Rows with zero views:", (df["views"] == 0).sum())

Rows with zero views: 0

## Preview the final Tableau-ready fields

In [23]:
df[[
    "video_id",
    "trending_date",
    "Trending_Month",
    "Trending_Week",
    "Trending_Year",
    "title",
    "channel_title",
    "Category",
    "views",
    "likes",
    "comment_count",
    "Region"
]].head(20)

,video_id,trending_date,Trending_Month,Trending_Week,Trending_Year,title,channel_title,Category,views,likes,comment_count,Region
0,n1WpP7iowLc,2017-11-14,2017-11,2017-11-13/2017-11-19,2017,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,Music,17158579,787425,125882,Canada
1,0dBIkQ4Mz1M,2017-11-14,2017-11,2017-11-13/2017-11-19,2017,PLUSH - Bad Unboxing Fan Mail,iDubbbzTV,Comedy,1014651,127794,13030,Canada
2,5qpjK5DgCt4,2017-11-14,2017-11,2017-11-13/2017-11-19,2017,"Racist Superman | Rudy Mancuso, King Bach & Le...",Rudy Mancuso,Comedy,3191434,146035,8181,Canada
3,d380meD0W0M,2017-11-14,2017-11,2017-11-13/2017-11-19,2017,I Dare You: GOING BALD!?,nigahiga,Entertainment,2095828,132239,17518,Canada
4,2Vv-BfVoq4g,2017-11-14,2017-11,2017-11-13/2017-11-19,2017,Ed Sheeran - Perfect (Official Music Video),Ed Sheeran,Music,33523622,1634130,85067,Canada
5,0yIWz1XEeyc,2017-11-14,2017-11,2017-11-13/2017-11-19,2017,Jake Paul Says Alissa Violet CHEATED with LOGA...,DramaAlert,News & Politics,1309699,103755,12143,Canada
6,_uM5kFfkhB8,2017-11-14,2017-11,2017-11-13/2017-11-19,2017,Vanoss Superhero School - New Students,VanossGaming,Comedy,2987945,187464,26629,Canada
7,2kyS6SvSYSE,2017-11-14,2017-11,2017-11-13/2017-11-19,2017,WE WANT TO TALK ABOUT OUR MARRIAGE,CaseyNeistat,People & Blogs,748374,57534,15959,Canada
8,JzCsM1vtn78,2017-11-14,2017-11,2017-11-13/2017-11-19,2017,THE LOGANG MADE HISTORY. LOL. AGAIN.,Logan Paul Vlogs,Entertainment,4477587,292837,36391,Canada
9,43sm-QwLcx4,2017-11-14,2017-11,2017-11-13/2017-11-19,2017,Finally Sheldon is winning an argument about t...,Sheikh Musa,People & Blogs,505161,4135,1484,Canada
10,H1KBHFXm2Bg,2017-11-14,2017-11,2017-11-13/2017-11-19,2017,21 Savage - Bank Account (Official Music Video),21 Savage,Music,5068229,263596,28976,Canada
11,U3xLOo-CNwo,2017-11-14,2017-11,2017-11-13/2017-11-19,2017,12 Weird Ways To Sneak Food Into Class / Back ...,Troom Troom,Howto & Style,3153224,28451,3312,Canada
12,FyZMnhUtLfE,2017-11-14,2017-11,2017-11-13/2017-11-19,2017,猎场 | Game Of Hunting 12【TV版】（胡歌、張嘉譯、祖峰等主演）,大劇獨播,Film & Animation,158815,218,186,Canada
13,7MxiQ4v0EnE,2017-11-14,2017-11,2017-11-13/2017-11-19,2017,Daang ( Full Video ) | Mankirt Aulakh | Sukh S...,Speed Records,Music,5718766,127477,8063,Canada
14,LUzsOyWp9lw,2017-11-14,2017-11,2017-11-13/2017-11-19,2017,YOUTUBERS REACT TO TOP 10 TWITTER ACCOUNTS OF ...,FBE,Entertainment,960747,31810,5335,Canada
15,AS9-ITLhQxo,2017-11-14,2017-11,2017-11-13/2017-11-19,2017,I Hired An MI6 Spy To Help Me Disappear,BuzzFeedBlue,People & Blogs,1531218,53961,4277,Canada
16,gifPYwArCVQ,2017-11-14,2017-11,2017-11-13/2017-11-19,2017,Fake Pet Smart Employee Prank!,NELK,Comedy,557883,44558,9619,Canada
17,8NHA23f7LvU,2017-11-14,2017-11,2017-11-13/2017-11-19,2017,Jason Momoa Wows Hugh Grant With Some Dothraki...,The Graham Norton Show,Entertainment,1496225,16116,605,Canada
18,fy-CuCzaPp8,2017-11-14,2017-11,2017-11-13/2017-11-19,2017,Rooster Teeth Animated Adventures - Drunk Baby...,Rooster Teeth,Film & Animation,308568,19541,495,Canada
19,kzwfHumJyYc,2017-11-14,2017-11,2017-11-13/2017-11-19,2017,Sharry Mann: Cute Munda ( Song Teaser) | Parmi...,Lokdhun Punjabi,Film & Animation,1096327,33966,882,Canada

## Save the final Tableau-ready dataset

In [24]:
df.to_csv("youtube_engagement_ready.csv", index=False)
print("Saved as youtube_engagement_ready.csv")

Saved as youtube_engagement_ready.csv

In [25]:
from google.colab import files
files.download("youtube_engagement_ready.csv")